### ISSUE TITLE
i get a error of list index out of range

### ISSUE THREAD

**Issue by zeelsheladiya** [Soumi7/Table_Data_Extraction#1]
i am trying to run your program but this part ( l[indexing].append(rows[i][j]) ) show me this out of bound error

**Comment by zeelsheladiya** [comment]
it solved !

**Comment by Soumi7** [comment]
Did you require changing any code? @zeelsheladiya

**Comment by zeelsheladiya** [comment]
Yes

**Comment by Soumi7** [comment]
You can leave a PR for people having the same issue.

**Comment by jeganrajrajan** [comment]
Thanks for the module. Still I'm also facing the same issue. (list index out of range)

**Comment by aschweng72** [comment]
@zeelsheladiya could you share the changes you made in the code? I am getting the same error as you
